### ISSUE TITLE
Error on sbJSON read

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#118]
Getting "sbJson schema version" is not supported when reading sbJSON. sbJSON doesn't support versioning, so we shouldn't ever get this error in practice.

**Comment by jlblcc** [comment]
Looks like all the tests that would normally catch this are disabled.

**Comment by stansmith907** [comment]
I tack on the version object in the reader.  I did this because I thought I remembered hearing the Fort was working on a version 2 of sbJson.  It shouldn't get in the way of any submitted sbJson.  I have it loaded the test examples because they don't come in through the code at front door, I can remove it if its bugging you.  But it's not really a bug.

**Comment by jlblcc** [comment]
That's fine but it's preventing translation in v2.1.1.

```
readerRequested: sbJson
readerVersionRequested: 0.0.0
readerVersionUsed: 0.1.0
readerStructurePass: false
readerStructureMessages: ["sbJson schema version '' is not supported"]
readerValidationLevel: normal
readerValidationPass: true
readerValidationMessages: []
readerExecutionPass: true
readerExecutionMessages: []
writerRequested: mdJson
writerPass: true
writerMessages: []
writerOutputFormat: 
writerOutput: 
writerShowTags: false
writerCSSlink: 
writerMissingIdCount: _000
translatorVersion: 2.1.1
```

**Comment by stansmith907** [comment]
Did you just bump the version?  Yeah, had not tested against the new version numbers.  I'll just take that stuff out.

**Comment by stansmith907** [comment]
Okay, got that straightened out.  
* the version bump to sbJson reader triggered failure
* I stripped out all the sbJson versioning code since it will not likely ever be versioned
* that caused a problem in the HTML writer which expects schema information to include in its report
* I added schema information directly for the sbJson reader, which no longer relies on schema information from the input file
