### ISSUE TITLE
GeoJSON for geographicElement is parsed as a string or not at all

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#133]
When converting to mdJSON:

- [ ] The [demo](http://mdtranslator.adiwg.org/api/v2/demo) FGDC returns an empty extent object (should have a bounding box).
- [ ] The [full text example](https://github.com/adiwg/mdTranslator/blob/master/test/readers/fgdc/testData/fgdc_fullRecord.xml) returns a JSON string (quotes escaped).

**Comment by stansmith907** [comment]
Found and fixed a few issues.

1. GeoJson entered through mdJson is JSON.parse'd along with the mdJson on reading.  So stays parsed until output.  I was converting the GeoJson built by the FGDC reader to JSON, which was thus being converted to JSON a second time on output.  
2. Empty objects and maps were not displaying because by the nativeGeoJson object for GeographicExtent needed to be an array not a scalar. In all other occurrences of nativeGeoJson it is a scalar.
