### ISSUE TITLE
Suggest removing logo images from mdJSON->sbJSON translation

### ISSUE THREAD

**Issue by zephyrr** [adiwg/mdTranslator#168]
The logos embedded in sbJSON seriously bulk up that metadata file (especially with one copy per reference, meaning sometimes many copies of the same logo embedded in the file).  This currently is a pain for manually reviewing the JSON, but it will also slow down bulk retrieval by DJ Case (whether or not ScienceBase implements a special function for that).

Since I don't see anywhere that ScienceBase displays this image, why not omit it from the translation to sbJSON?

**Comment by dwalt** [comment]
Images are used when sbJSON is used to create a contact page:  [https://www.sciencebase.gov/catalog/catalogParty/show?partyId=18199](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.sciencebase.gov%2Fcatalog%2FcatalogParty%2Fshow%3FpartyId%3D18199&data=05%7C01%7Cdwalworth%40usgs.gov%7Caa93af465e5840387c4308da809ced0f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637963708723973720%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YOOztZu4zbnGCH8pwRIvcGe76RmMr2M6KwtRtlyH5ac%3D&reserved=0). The contact page in turn can be referenced by other item pages for attribution.

Known use cases of mdJSON would rarely result in an sbJSON file embedded with a multitude of contact logos, particularly if contacts are normalized in mdEditor. Unclear of how poster is using mdJSON-sbJSON translation that would result in issues for review and unacceptable file bulk due to the presence of images.

**Comment by hmaier-fws** [comment]
Logos are supported by sbJSON "[contact objects](https://my.usgs.gov/confluence/display/sciencebase/ScienceBase+Item+Core+Model#ScienceBaseItemCoreModel-contactObject)" and the feature complies with current requirements. "data:" is a valid URI scheme as per https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml and https://www.rfc-editor.org/rfc/rfc2397.html
