### ISSUE TITLE
Issue warning when contact is not found

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#187]
Currently we generally ignore instances when contacts are not found in the contacts array(getContact methods). It would be useful to issue a WARNING when this occurs, especially when #183 is implemented.

**Comment by stansmith907** [comment]
Looks like this is true for the mdJson reader.  Contacts are always (I think) referenced through `responsibleParty` in mdJson.  Currently the reader only checks to see that a party (contactId) was specified, not that the `contactId` is valid.  I can add the additional check.  

FGDC and sbJson readers do not draw from the contacts array.  For these readers contacts are added as they are encountered in the input file.  

Writers are also different.  They always check for valid `contactId` since they draw from the contacts array to write information to the selected standard.

**Comment by jlblcc** [comment]
I have some reports of this happening where a contact has a memberOfOrganization array and the id within that array is not found anywhere within the contacts array. We can't check for this in the mdJSON schema, so we might want to issue a warning during the translation. Maybe when reading mdJSON?

**Comment by stansmith907** [comment]
Now I see the confusion.  `responsibleParty` has `party` which has `organizationMembers`.  These are checked in every use of responsible party in mdJson.  `contact` has `memberOfOrganization`.  These are not checked; the problem being that all contacts would need to be loaded before the check could be valid.  So, `memberOfOrganization` is *not* check when a contact is added.

To test `memberOfOrganization` for valid `contactId`(s) I will need to add a post-contact-processing module into the workflow.  Which I will do.  :smiley:

**Comment by stansmith907** [comment]
Done.
