### ISSUE TITLE
Enumerated Value lists Description written to the ISO 19110 output?

### ISSUE THREAD

**Issue by palmerj** [adiwg/mdTranslator#218]
I tried to translate a valid fgdc XML file to ISO 19110 XML and the enumerated values list descriptions were not being created. See file here https://gist.github.com/palmerj/5b04d52307f2a4d7c991759bc8ce77d9

**Comment by jlblcc** [comment]
Looks like the FGDC reader is assigning the _first overall_ domain(first domain from first parsed attribute) to each attribute instead of the the first domain assigned to the _individual_ attribute (the mdTranslator and mdJSON spec only support one domain assignment for each attribute). 

Will adjust the logic to use the first domain assigned to each individual attribute in FGDC (I would think that having multiple domains assigned to an attribute is more of an edge case, excepting range domains which are handled differently).  Look for the patch in _v2.17.1_. @palmerj Thanks for reporting this.

**Comment by palmerj** [comment]
Thanks heaps @jlblcc

**Comment by dwalt** [comment]
Just a heads up, but we quite often have multiple domains per attribute.
This may be to account for coded values within a numeric field, resulting
in a range domain and a codeset domain.

**Comment by jlblcc** [comment]
@dwalt The FGDC reader handles range domains differently. In fact, they are not interpreted as "domains" at all. The mdJSON schema has the [valueRange](https://mdtools.adiwg.org/#viewer-page?v=4-0-10-0-8-0-17) property which the CSDGM range domains map to. Therefore, if you have a single codeset domain and any number of range domains, you should not lose anything in the translation.

**Comment by dwalt** [comment]
Good to know, thanks for the clarification.
